version: '3.8'

services:
  # Base de datos MySQL
  db:
    image: mysql:8.0
    container_name: todo_tops_mysql
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - todo_tops_network

  # WordPress
  wordpress:
    depends_on:
      - db
    image: wordpress:6.3-fpm-alpine
    container_name: todo_tops_wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - todo_tops_network

  # Nginx
  nginx:
    depends_on:
      - wordpress
    image: nginx:1.24-alpine
    container_name: todo_tops_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - todo_tops_network

  # phpMyAdmin (opcional, para gestión de BD)
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:5.2
    container_name: todo_tops_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - todo_tops_network

# Volúmenes persistentes
volumes:
  db_data:
    driver: local
  wordpress_data:
    driver: local

# Red para comunicación entre contenedores
networks:
  todo_tops_network:
    driver: bridge